[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# ffi = true

mappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
    'chainaccelorg/contracts=lib/foundry-contracts/contracts',
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[[profile.default.plugins]]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
